default_platform(:ios)

platform :ios do
  desc "Bump version number"
  lane :bump_version_number do
    increment_build_number
    commit_version_bump
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    build_app(scheme: "pomo")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
