default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    commit_version_bump
    build_app(scheme: "pomo")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
